#!/bin/bash
# Script to update frontend API configuration with the API endpoint

set -e

# Constants
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
FRONTEND_DIR="$(dirname "${SCRIPT_DIR}")"
API_CONFIG_FILE="${FRONTEND_DIR}/src/services/apiConfig.js"
API_ENDPOINT=""

# Functions
function print_help {
    echo "Usage: $0 [options]"
    echo "Options:"
    echo "  -h, --help                Show this help message"
    echo "  -e, --api-endpoint URL    Set API endpoint URL (required)"
    echo ""
    echo "Example:"
    echo "  $0 --api-endpoint https://abc123.execute-api.eu-west-2.amazonaws.com/prod/analyze"
}

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    key="$1"
    case $key in
        -h|--help)
            print_help
            exit 0
            ;;
        -e|--api-endpoint)
            API_ENDPOINT="$2"
            shift
            shift
            ;;
        *)
            echo "Unknown option: $1"
            print_help
            exit 1
            ;;
    esac
done

# Validate required parameters
if [ -z "$API_ENDPOINT" ]; then
    echo "Error: API endpoint URL is required"
    print_help
    exit 1
fi

# Create the API configuration file if it doesn't exist
if [ ! -d "$(dirname "${API_CONFIG_FILE}")" ]; then
    mkdir -p "$(dirname "${API_CONFIG_FILE}")"
fi

echo "Creating/updating API configuration file at ${API_CONFIG_FILE}..."

# Create or update the API configuration file
cat > "${API_CONFIG_FILE}" << EOF
/**
 * API Configuration for AITaskLens
 * This file is auto-generated by the deployment script
 * Last updated: $(date)
 */

const API_CONFIG = {
  baseURL: '${API_ENDPOINT}',
  headers: {
    'Content-Type': 'application/json',
    'Accept': 'application/json'
  },
  timeoutMs: 60000  // 60 seconds timeout
};

export default API_CONFIG;
EOF

# Create the API service file if it doesn't exist
API_SERVICE_FILE="${FRONTEND_DIR}/src/services/api.js"

if [ ! -f "${API_SERVICE_FILE}" ]; then
  echo "Creating API service file at ${API_SERVICE_FILE}..."
  
  cat > "${API_SERVICE_FILE}" << EOF
/**
 * API Service for AITaskLens
 * This file provides methods to interact with the backend API
 */

import API_CONFIG from './apiConfig';

// Helper function to handle API errors
const handleApiError = (error) => {
  console.error('API Error:', error);
  
  if (error.response) {
    // The request was made and the server responded with a status code
    // that falls out of the range of 2xx
    return Promise.reject({
      status: error.response.status,
      message: error.response.data.error || 'An error occurred',
      data: error.response.data
    });
  } else if (error.request) {
    // The request was made but no response was received
    return Promise.reject({
      status: 0,
      message: 'No response from server. Please check your connection.'
    });
  } else {
    // Something happened in setting up the request that triggered an Error
    return Promise.reject({
      status: 0,
      message: error.message || 'An unknown error occurred'
    });
  }
};

// API functions
const api = {
  /**
   * Analyze task based on answers to questions
   * @param {Object} answers - An object mapping question indices to answers
   * @returns {Promise} A promise that resolves to the analysis result
   */
  analyzeTask: async (answers) => {
    try {
      const response = await fetch(API_CONFIG.baseURL, {
        method: 'POST',
        headers: API_CONFIG.headers,
        body: JSON.stringify({ answers }),
        timeout: API_CONFIG.timeoutMs
      });
      
      if (!response.ok) {
        const errorData = await response.json();
        throw { 
          response: { 
            status: response.status, 
            data: errorData 
          } 
        };
      }
      
      return await response.json();
    } catch (error) {
      return handleApiError(error);
    }
  }
};

export default api;
EOF
fi

echo "Frontend API configuration updated successfully!"
echo ""
echo "Now you need to modify your React components to use the API service instead of mock data."
echo "Example usage in HomePage component:"
echo ""
echo "import api from '../services/api';"
echo ""
echo "// Then in your submit handler:"
echo "const response = await api.analyzeTask(answers);"