/**
 * API Configuration for AITaskLens
 * This file is auto-generated by the deployment script
 * Last updated: Sun May  4 05:48:00 BST 2025
 */

const API_CONFIG = {
  baseURL: 'https://wmh4jb996l.execute-api.eu-west-2.amazonaws.com/prod/analyze',
  headers: {
    'Content-Type': 'application/json',
    'Accept': 'application/json'
  },
  timeoutMs: 60000  // 60 seconds timeout
};

export default API_CONFIG;
